import React, { useState } from 'react';
import { Film, Lightbulb, Sparkles, Video, Loader2 } from 'lucide-react';
import { generateVideoFromStory } from '../services/geminiService';

interface StoryProps {
  insights: string;
  story: string;
}

export const Story: React.FC<StoryProps> = ({ insights, story }) => {
  const [videoUrl, setVideoUrl] = useState<string | null>(null);
  const [isGeneratingVideo, setIsGeneratingVideo] = useState(false);
  const [videoProgress, setVideoProgress] = useState<string>('');
  const [videoError, setVideoError] = useState<string | null>(null);

  const handleGenerateVideo = async () => {
    setIsGeneratingVideo(true);
    setVideoError(null);
    try {
      const url = await generateVideoFromStory(story, setVideoProgress);
      setVideoUrl(url);
    } catch (err: any) {
      setVideoError(err.message || "Failed to generate video");
    } finally {
      setIsGeneratingVideo(false);
    }
  };

  if (!insights && !story) return null;

  return (
    <div className="bg-white p-6 md:p-8 text-slate-900 border-t border-slate-200">
      <div className="max-w-7xl mx-auto space-y-8">
        
        {/* Header */}
        <div>
          <h1 className="text-3xl font-extrabold tracking-tight text-slate-900 mb-2 flex items-center gap-3">
            <Sparkles className="w-8 h-8 text-blue-500" />
            AI Insights & Story
          </h1>
          <p className="text-slate-500 font-medium">Cinematic narrative and data-driven insights generated by Gemini.</p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          
          {/* Insights Section */}
          <div className="lg:col-span-1 bg-amber-50/50 border border-amber-100 rounded-2xl p-6 shadow-sm">
            <h2 className="text-xl font-bold text-slate-800 mb-6 flex items-center gap-2 border-b border-amber-200/50 pb-4">
              <Lightbulb className="w-5 h-5 text-amber-500" />
              Key Insights
            </h2>
            <div className="prose prose-slate max-w-none text-sm leading-relaxed">
              {insights.split('\n').map((line, i) => {
                if (line.trim().startsWith('-') || line.trim().startsWith('*')) {
                  return <li key={i} className="mb-2 text-slate-700 font-medium">{line.replace(/^[-*]\s*/, '')}</li>;
                }
                return line.trim() ? <p key={i} className="mb-2 text-slate-700 font-medium">{line}</p> : null;
              })}
            </div>
          </div>

          {/* Cinematic Story Section */}
          <div className="lg:col-span-2 bg-blue-50/30 border border-blue-100 rounded-2xl p-8 shadow-sm relative overflow-hidden flex flex-col">
            <div className="absolute top-0 left-0 p-4 opacity-5 pointer-events-none">
              <Film className="w-48 h-48 text-blue-600" />
            </div>
            
            <div className="flex items-center justify-between mb-6 border-b border-blue-200/50 pb-4 relative z-10">
              <h2 className="text-xl font-bold text-slate-800 flex items-center gap-2">
                <Film className="w-5 h-5 text-blue-500" />
                Cinematic Story Script
              </h2>
              
              {!videoUrl && !isGeneratingVideo && (
                <button
                  onClick={handleGenerateVideo}
                  className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg text-sm font-semibold transition-colors shadow-sm"
                >
                  <Video className="w-4 h-4" />
                  Generate Video
                </button>
              )}
            </div>
            
            {isGeneratingVideo && (
              <div className="mb-6 bg-blue-100/50 border border-blue-200 rounded-xl p-6 flex flex-col items-center justify-center text-center relative z-10">
                <Loader2 className="w-8 h-8 text-blue-500 animate-spin mb-3" />
                <p className="text-blue-800 font-medium">{videoProgress}</p>
                <p className="text-blue-600/70 text-sm mt-2">Veo 3.1 is crafting your cinematic visualization...</p>
              </div>
            )}

            {videoError && (
              <div className="mb-6 bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-xl text-sm font-medium relative z-10">
                {videoError}
              </div>
            )}

            {videoUrl && (
              <div className="mb-6 rounded-xl overflow-hidden border border-slate-200 shadow-md relative z-10 bg-black aspect-video flex items-center justify-center">
                <video 
                  src={videoUrl} 
                  controls 
                  autoPlay 
                  className="w-full h-full object-contain"
                />
              </div>
            )}
            
            <div className="prose prose-slate max-w-none text-base leading-loose relative z-10 font-serif flex-1">
              {story.split('\n\n').map((paragraph, i) => (
                <p key={i} className="mb-6 text-slate-700 text-justify">
                  {paragraph}
                </p>
              ))}
            </div>
          </div>

        </div>
      </div>
    </div>
  );
};
